### ISSUE TITLE
Moving from Heart 2.4.0 to Heart 2.4.1 gives this error

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#78]
![image](https://github.com/pancake-llc/foundation/assets/63500913/1e3d15f8-a545-4ff9-8642-3e820604c0c1)

System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ApiUpdater.MovedFromOptimizer.Program.CollectMovedFromTypeNamesFromAssembly(String assemblyPath, StreamWriter outputFile, IAPIUpdaterListener logger)
   at ApiUpdater.MovedFromOptimizer.Program.RealMain(String[] args)
   at ApiUpdater.MovedFromOptimizer.Program.Main(String[] args)

**Comment by IAFahim** [comment]
I see you didn't release 2.4.0 I was getting this error at 2.4.1, so I changed a version to 2.4.0 (2.4.1 → 2.4.0) to see if the error goes away.

**Comment by yenmoc** [comment]
Can you try updating to version 2.4.2? I tried to reproduce the error by installing version 2.4.0 and then upgrading to 2.4.1 but it doesn't seem to produce any errors.

**Comment by IAFahim** [comment]
Nope, 2.4.2 works fine.

**Comment by IAFahim** [comment]
You are really fastt
